services:
  configserver:
    image: "iritik/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m

    networks:
      - bank


  accounts:
    image: "iritik/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m

    networks:
      - bank

    environment:
      SPRING_APPLICATION_NAME: 
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default


  loans:
    image: "iritik/loan-service:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m

    networks:
      - bank


  cards:
    image: "iritik/cards-service:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m

    networks:
      - bank

networks:
  bank:
    driver: "bridge"